#ifndef BUILDINGS
#define BUILDINGS

#include <ace/types.h>

typedef enum __attribute__((__packed__)) {
    BUILDING_HUMAN_SMITHY = 21,
    BUILDING_CONSTRUCTION_SMALL = 22,
    BUILDING_HUMAN_FARM = 23,
    BUILDING_HUMAN_BARRACKS = 24,
    BUILDING_HUMAN_LUMBERMILL = 28,
    BUILDING_HUMAN_CHURCH = 32,
    BUILDING_HUMAN_STABLES = 36,
    BUILDING_CONSTRUCTION_LARGE = 40,
    BUILDING_HUMAN_TOWNHALL = 44,
    BUILDING_HUMAN_TOWER = 48,
    BUILDING_ORC_FARM,
    BUILDING_ORC_BARRACKS,
    BUILDING_ORC_LUMBERMILL,
    BUILDING_ORC_SMITHY,
    BUILDING_ORC_TOWNHALL,
    BUILDING_ORC_STABLES,
    BUILDING_ORC_CHURCH,
    BUILDING_ORC_TOWER,
    BUILDING_GOLD_MINE,
} BuildingType;
_Static_assert(sizeof(BuildingType) == sizeof(UBYTE), "not 1 byte");

#endif
