#ifndef BUILDINGS
#define BUILDINGS

#include <ace/types.h>

typedef enum __attribute__((__packed__)) {
    BUILDING_HUMAN_FARM,
    BUILDING_HUMAN_BARRACKS,
    BUILDING_HUMAN_LUMBERMILL,
    BUILDING_HUMAN_SMITHY,
    BUILDING_HUMAN_TOWNHALL,
    BUILDING_HUMAN_STABLES,
    BUILDING_HUMAN_CHURCH,
    BUILDING_HUMAN_TOWER,
    BUILDING_ORC_FARM,
    BUILDING_ORC_BARRACKS,
    BUILDING_ORC_LUMBERMILL,
    BUILDING_ORC_SMITHY,
    BUILDING_ORC_TOWNHALL,
    BUILDING_ORC_STABLES,
    BUILDING_ORC_CHURCH,
    BUILDING_ORC_TOWER,
    BUILDING_GOLD_MINE,
} BuildingType;
_Static_assert(sizeof(BuildingType) == sizeof(UBYTE), "not 1 byte");

#endif
